x <- c(4,3,6,3,3,4,3,2,3,3)
y <- c(3,NA,4,4,3,2,1,2,3,4)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)


x <- c(4,3,6,3,3,4,3,NA,3,3)
y <- c(3,NA,4,4,3,2,1,2,3,4)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(4,NA,6,3,3,4,3,2,3,3)
y <- c(3,5,4,4,3,2,1,2,3,4)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(4,3,6,3,3,4,3,2,3,3)
y <- c(3,5,4,4,3,2,1,2,3,4)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(NA,5,NA,3)
y <- c(3,NA,4,NA)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(NA,5,NA,3,4)
y <- c(3,NA,4,NA,3)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(NA,5,NA,3,1,2,3)
y <- c(3,NA,4,NA,2,4,6)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

x <- c(NA,5,2,NA,3,NA,4,NA,3,1,2,3)
y <- c(3,NA,4,4,6,5,NA,7,NA,2,4,6)
modttest(x,y)
corrected_Z(x,y)
homoMLE(x,y)
heteMLE(x,y)
weighted.z.test(x,y)
cor_Z(x,y)

